version: "3.7"
services:

  issuer-verifier-acapy:
    image: ${ACAPY_IMAGE}
    entrypoint: /bin/bash
    command: [
        "-c",
        "sleep 10;
        aca-py start \
        --auto-provision
        --admin 0.0.0.0 10000 \
        --inbound-transport http 0.0.0.0 10001 \
        --outbound-transport http \
        --endpoint http://issuer-verifier-nginx:10001 \
        --genesis-url ${LEDGER_GENESIS} \
        --ledger-pool-name ${LEDGER_POOL_NAME} \
        --invite-base-url didcomm://aries_connection_invitation \
        --admin-insecure-mode \
        --label issuer_verifier_acapy \
        --wallet-type ${WALLET_TYPE} \
        --wallet-name ${POSTGRES_DB} \
        --wallet-key key \
        --wallet-storage-type postgres_storage \
        --wallet-storage-config '{\"url\":\"issuer-verifier-wallet-db:5000\",\"max_connections\":${MAX_WALLET_CONNECTIONS_PER_ACAPY}}' \
        --wallet-storage-creds '{\"account\":\"${POSTGRES_USER}\",\"password\":\"${POSTGRES_PASSWORD}\",\"admin_account\":\"${POSTGRES_USER}\",\"admin_password\":\"${POSTGRES_PASSWORD}\"}' \
        --auto-ping-connection \
        --auto-verify-presentation \
        --invite-public \
        --public-invites \
        --invite-multi-use \
        --tails-server-base-url ${ACAPY_TAILS_SERVER_BASE_URL} \
        --seed ${ISSUER_DID_SEED} \
        --log-level ${ACAPY_LOG_LEVEL} \
        --webhook-url ${LOAD_GENERATOR_WEBHOOK_ENDPOINT} \
        ${ACAPY_DEBUG_OPTIONS}"
    ]
    networks:
      - aries-load-test
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "50m"
    restart: always

  issuer-verifier-nginx:
    container_name: issuer-verifier-nginx
    image: nginx:latest
    volumes:
      - ./nginx-issuer-verifier.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - issuer-verifier-acapy
    ports:
      - 10000:10000
    networks:
      - aries-load-test

  holder-acapy-1:
    container_name: holder-acapy-1
    image: ${ACAPY_IMAGE}
    entrypoint: /bin/bash
    command: [
        "-c",
        "sleep 10;
        aca-py start \
        --auto-provision \
        --inbound-transport http 0.0.0.0 10011 \
        --outbound-transport http \
        --admin 0.0.0.0 10010 \
        --endpoint http://holder-acapy-1:10011 \
        --genesis-url ${LEDGER_GENESIS} \
        --ledger-pool-name $LEDGER_POOL_NAME \
        --ledger-pool-name ${LEDGER_POOL_NAME} \
        --admin-insecure-mode \
        --label holder_acapy \
        --wallet-type ${WALLET_TYPE} \
        --wallet-name wallet_db \
        --wallet-key key \
        --wallet-storage-type default \
        --auto-accept-invites \
        --invite-public \
        --public-invites \
        --auto-accept-requests \
        --auto-ping-connection \
        --auto-respond-credential-offer \
        --auto-respond-credential-proposal \
        --auto-respond-credential-request \
        --auto-respond-messages \
        --auto-store-credential \
        --auto-respond-presentation-request \
        --auto-respond-presentation-proposal \
        --auto-verify-presentation \
        --log-level ${ACAPY_LOG_LEVEL} \
        ${ACAPY_DEBUG_OPTIONS}"
    ]
    depends_on:
      - tails-server
    ports:
      - 10110:10010
      - 10111:10011
    networks:
      - aries-load-test
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "50m"
    restart: always

  holder-acapy-2:
    container_name: holder-acapy-2
    image: ${ACAPY_IMAGE}
    entrypoint: /bin/bash
    command: [
        "-c",
        "sleep 10;
        aca-py start \
        --auto-provision \
        --inbound-transport http 0.0.0.0 10011 \
        --outbound-transport http \
        --admin 0.0.0.0 10010 \
        --endpoint http://holder-acapy-2:10011 \
        --genesis-url ${LEDGER_GENESIS} \
        --ledger-pool-name $LEDGER_POOL_NAME \
        --ledger-pool-name ${LEDGER_POOL_NAME} \
        --admin-insecure-mode \
        --label holder_acapy \
        --wallet-type ${WALLET_TYPE} \
        --wallet-name wallet_db \
        --wallet-key key \
        --wallet-storage-type default \
        --auto-accept-invites \
        --invite-public \
        --public-invites \
        --auto-accept-requests \
        --auto-ping-connection \
        --auto-respond-credential-offer \
        --auto-respond-credential-proposal \
        --auto-respond-credential-request \
        --auto-respond-messages \
        --auto-store-credential \
        --auto-respond-presentation-request \
        --auto-respond-presentation-proposal \
        --auto-verify-presentation \
        --log-level ${ACAPY_LOG_LEVEL} \
        ${ACAPY_DEBUG_OPTIONS}"
    ]
    depends_on:
      - tails-server
    ports:
      - 10210:10010
      - 10211:10011
    networks:
      - aries-load-test
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "50m"
    restart: always

  holder-acapy-3:
    container_name: holder-acapy-3
    image: ${ACAPY_IMAGE}
    entrypoint: /bin/bash
    command: [
        "-c",
        "sleep 10;
        aca-py start \
        --auto-provision \
        --inbound-transport http 0.0.0.0 10011 \
        --outbound-transport http \
        --admin 0.0.0.0 10010 \
        --endpoint http://holder-acapy-3:10011 \
        --genesis-url ${LEDGER_GENESIS} \
        --ledger-pool-name $LEDGER_POOL_NAME \
        --ledger-pool-name ${LEDGER_POOL_NAME} \
        --admin-insecure-mode \
        --label holder_acapy \
        --wallet-type ${WALLET_TYPE} \
        --wallet-name wallet_db \
        --wallet-key key \
        --wallet-storage-type default \
        --auto-accept-invites \
        --invite-public \
        --public-invites \
        --auto-accept-requests \
        --auto-ping-connection \
        --auto-respond-credential-offer \
        --auto-respond-credential-proposal \
        --auto-respond-credential-request \
        --auto-respond-messages \
        --auto-store-credential \
        --auto-respond-presentation-request \
        --auto-respond-presentation-proposal \
        --auto-verify-presentation \
        --log-level ${ACAPY_LOG_LEVEL} \
        ${ACAPY_DEBUG_OPTIONS}"
    ]
    depends_on:
      - tails-server
    ports:
      - 10310:10010
      - 10311:10011
    networks:
      - aries-load-test
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "50m"
    restart: always

  holder-acapy-4:
    container_name: holder-acapy-4
    image: ${ACAPY_IMAGE}
    entrypoint: /bin/bash
    command: [
        "-c",
        "sleep 10;
        aca-py start \
        --auto-provision \
        --inbound-transport http 0.0.0.0 10011 \
        --outbound-transport http \
        --admin 0.0.0.0 10010 \
        --endpoint http://holder-acapy-4:10011 \
        --genesis-url ${LEDGER_GENESIS} \
        --ledger-pool-name $LEDGER_POOL_NAME \
        --ledger-pool-name ${LEDGER_POOL_NAME} \
        --admin-insecure-mode \
        --label holder_acapy \
        --wallet-type ${WALLET_TYPE} \
        --wallet-name wallet_db \
        --wallet-key key \
        --wallet-storage-type default \
        --auto-accept-invites \
        --invite-public \
        --public-invites \
        --auto-accept-requests \
        --auto-ping-connection \
        --auto-respond-credential-offer \
        --auto-respond-credential-proposal \
        --auto-respond-credential-request \
        --auto-respond-messages \
        --auto-store-credential \
        --auto-respond-presentation-request \
        --auto-respond-presentation-proposal \
        --auto-verify-presentation \
        --log-level ${ACAPY_LOG_LEVEL} \
        ${ACAPY_DEBUG_OPTIONS}"
    ]
    depends_on:
      - tails-server
    ports:
      - 10410:10010
      - 10411:10011
    networks:
      - aries-load-test
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "50m"
    restart: always

  holder-acapy-5:
    container_name: holder-acapy-5
    image: ${ACAPY_IMAGE}
    entrypoint: /bin/bash
    command: [
        "-c",
        "sleep 10;
        aca-py start \
        --auto-provision \
        --inbound-transport http 0.0.0.0 10011 \
        --outbound-transport http \
        --admin 0.0.0.0 10010 \
        --endpoint http://holder-acapy-5:10011 \
        --genesis-url ${LEDGER_GENESIS} \
        --ledger-pool-name $LEDGER_POOL_NAME \
        --ledger-pool-name ${LEDGER_POOL_NAME} \
        --admin-insecure-mode \
        --label holder_acapy \
        --wallet-type ${WALLET_TYPE} \
        --wallet-name wallet_db \
        --wallet-key key \
        --wallet-storage-type default \
        --auto-accept-invites \
        --invite-public \
        --public-invites \
        --auto-accept-requests \
        --auto-ping-connection \
        --auto-respond-credential-offer \
        --auto-respond-credential-proposal \
        --auto-respond-credential-request \
        --auto-respond-messages \
        --auto-store-credential \
        --auto-respond-presentation-request \
        --auto-respond-presentation-proposal \
        --auto-verify-presentation \
        --log-level ${ACAPY_LOG_LEVEL} \
        ${ACAPY_DEBUG_OPTIONS}"
    ]
    depends_on:
      - tails-server
    ports:
      - 10510:10010
      - 10511:10011
    networks:
      - aries-load-test
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "50m"
    restart: always

  holder-acapy-6:
    container_name: holder-acapy-6
    image: ${ACAPY_IMAGE}
    entrypoint: /bin/bash
    command: [
        "-c",
        "sleep 10;
        aca-py start \
        --auto-provision \
        --inbound-transport http 0.0.0.0 10011 \
        --outbound-transport http \
        --admin 0.0.0.0 10010 \
        --endpoint http://holder-acapy-6:10011 \
        --genesis-url ${LEDGER_GENESIS} \
        --ledger-pool-name $LEDGER_POOL_NAME \
        --ledger-pool-name ${LEDGER_POOL_NAME} \
        --admin-insecure-mode \
        --label holder_acapy \
        --wallet-type ${WALLET_TYPE} \
        --wallet-name wallet_db \
        --wallet-key key \
        --wallet-storage-type default \
        --auto-accept-invites \
        --invite-public \
        --public-invites \
        --auto-accept-requests \
        --auto-ping-connection \
        --auto-respond-credential-offer \
        --auto-respond-credential-proposal \
        --auto-respond-credential-request \
        --auto-respond-messages \
        --auto-store-credential \
        --auto-respond-presentation-request \
        --auto-respond-presentation-proposal \
        --auto-verify-presentation \
        --log-level ${ACAPY_LOG_LEVEL} \
        ${ACAPY_DEBUG_OPTIONS}"
    ]
    depends_on:
      - tails-server
    ports:
      - 10610:10010
      - 10611:10011
    networks:
      - aries-load-test
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "50m"
    restart: always

  holder-acapy-7:
    container_name: holder-acapy-7
    image: ${ACAPY_IMAGE}
    entrypoint: /bin/bash
    command: [
        "-c",
        "sleep 10;
        aca-py start \
        --auto-provision \
        --inbound-transport http 0.0.0.0 10011 \
        --outbound-transport http \
        --admin 0.0.0.0 10010 \
        --endpoint http://holder-acapy-7:10011 \
        --genesis-url ${LEDGER_GENESIS} \
        --ledger-pool-name $LEDGER_POOL_NAME \
        --ledger-pool-name ${LEDGER_POOL_NAME} \
        --admin-insecure-mode \
        --label holder_acapy \
        --wallet-type ${WALLET_TYPE} \
        --wallet-name wallet_db \
        --wallet-key key \
        --wallet-storage-type default \
        --auto-accept-invites \
        --invite-public \
        --public-invites \
        --auto-accept-requests \
        --auto-ping-connection \
        --auto-respond-credential-offer \
        --auto-respond-credential-proposal \
        --auto-respond-credential-request \
        --auto-respond-messages \
        --auto-store-credential \
        --auto-respond-presentation-request \
        --auto-respond-presentation-proposal \
        --auto-verify-presentation \
        --log-level ${ACAPY_LOG_LEVEL} \
        ${ACAPY_DEBUG_OPTIONS}"
    ]
    depends_on:
      - tails-server
    ports:
      - 10710:10010
      - 10711:10011
    networks:
      - aries-load-test
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "50m"
    restart: always

  holder-acapy-8:
    container_name: holder-acapy-8
    image: ${ACAPY_IMAGE}
    entrypoint: /bin/bash
    command: [
        "-c",
        "sleep 10;
        aca-py start \
        --auto-provision \
        --inbound-transport http 0.0.0.0 10011 \
        --outbound-transport http \
        --admin 0.0.0.0 10010 \
        --endpoint http://holder-acapy-8:10011 \
        --genesis-url ${LEDGER_GENESIS} \
        --ledger-pool-name $LEDGER_POOL_NAME \
        --ledger-pool-name ${LEDGER_POOL_NAME} \
        --admin-insecure-mode \
        --label holder_acapy \
        --wallet-type ${WALLET_TYPE} \
        --wallet-name wallet_db \
        --wallet-key key \
        --wallet-storage-type default \
        --auto-accept-invites \
        --invite-public \
        --public-invites \
        --auto-accept-requests \
        --auto-ping-connection \
        --auto-respond-credential-offer \
        --auto-respond-credential-proposal \
        --auto-respond-credential-request \
        --auto-respond-messages \
        --auto-store-credential \
        --auto-respond-presentation-request \
        --auto-respond-presentation-proposal \
        --auto-verify-presentation \
        --log-level ${ACAPY_LOG_LEVEL} \
        ${ACAPY_DEBUG_OPTIONS}"
    ]
    depends_on:
      - tails-server
    ports:
      - 10810:10010
      - 10811:10011
    networks:
      - aries-load-test
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "50m"
    restart: always

  holder-acapy-9:
    container_name: holder-acapy-9
    image: ${ACAPY_IMAGE}
    entrypoint: /bin/bash
    command: [
        "-c",
        "sleep 10;
        aca-py start \
        --auto-provision \
        --inbound-transport http 0.0.0.0 10011 \
        --outbound-transport http \
        --admin 0.0.0.0 10010 \
        --endpoint http://holder-acapy-9:10011 \
        --genesis-url ${LEDGER_GENESIS} \
        --ledger-pool-name $LEDGER_POOL_NAME \
        --ledger-pool-name ${LEDGER_POOL_NAME} \
        --admin-insecure-mode \
        --label holder_acapy \
        --wallet-type ${WALLET_TYPE} \
        --wallet-name wallet_db \
        --wallet-key key \
        --wallet-storage-type default \
        --auto-accept-invites \
        --invite-public \
        --public-invites \
        --auto-accept-requests \
        --auto-ping-connection \
        --auto-respond-credential-offer \
        --auto-respond-credential-proposal \
        --auto-respond-credential-request \
        --auto-respond-messages \
        --auto-store-credential \
        --auto-respond-presentation-request \
        --auto-respond-presentation-proposal \
        --auto-verify-presentation \
        --log-level ${ACAPY_LOG_LEVEL} \
        ${ACAPY_DEBUG_OPTIONS}"
    ]
    depends_on:
      - tails-server
    ports:
      - 10910:10010
      - 10911:10011
    networks:
      - aries-load-test
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "50m"
    restart: always

  holder-acapy-10:
    container_name: holder-acapy-10
    image: ${ACAPY_IMAGE}
    entrypoint: /bin/bash
    command: [
        "-c",
        "sleep 10;
        aca-py start \
        --auto-provision \
        --inbound-transport http 0.0.0.0 10011 \
        --outbound-transport http \
        --admin 0.0.0.0 10010 \
        --endpoint http://holder-acapy-10:10011 \
        --genesis-url ${LEDGER_GENESIS} \
        --ledger-pool-name $LEDGER_POOL_NAME \
        --ledger-pool-name ${LEDGER_POOL_NAME} \
        --admin-insecure-mode \
        --label holder_acapy \
        --wallet-type ${WALLET_TYPE} \
        --wallet-name wallet_db \
        --wallet-key key \
        --wallet-storage-type default \
        --auto-accept-invites \
        --invite-public \
        --public-invites \
        --auto-accept-requests \
        --auto-ping-connection \
        --auto-respond-credential-offer \
        --auto-respond-credential-proposal \
        --auto-respond-credential-request \
        --auto-respond-messages \
        --auto-store-credential \
        --auto-respond-presentation-request \
        --auto-respond-presentation-proposal \
        --auto-verify-presentation \
        --log-level ${ACAPY_LOG_LEVEL} \
        ${ACAPY_DEBUG_OPTIONS}"
    ]
    depends_on:
      - tails-server
    ports:
      - 11010:10010
      - 11011:10011
    networks:
      - aries-load-test
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "50m"
    restart: always

  tails-server:
    container_name: tails-server
    build:
      context: ./indy-tails-server
      dockerfile: docker/Dockerfile.tails-server
    command: >
      tails-server
        --host 0.0.0.0
        --port 6543
        --storage-path /tmp/tails-files
        --log-level INFO

    volumes:
      - tails-server-volume:/home/indy/tails-files
    ports:
      - 6543:6543
    networks:
      - aries-load-test
    restart: always

networks:
  aries-load-test:
    external: true
    name: aries-load-test

volumes:
  tails-server-volume:
