spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/
        username: postgres
        password: postgres
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher # required for the Swagger UI to work

logging:
    config: classpath:logback-spring.xml

issuer-verifier:
    acapy:
        api-key:
        url: 'http://localhost:10000'
        http-timeout: 60
    wallet-db-name: wallet_db

holder:
    acapy:
        api-key:
        url: 'http://localhost:10010'
        http-timeout: 60

test-runners:
    max-parallel-iterations-runner:
        active: true
        number-of-total-iterations: 100
        number-of-parallel-iterations: 5
    constant-load-runner:
        active: false
        number-of-total-iterations: 100
        number-of-iterations-per-minute: 30
        core-thread-pool-size: 4

test-flows:
    full-flow:
        active: true
        use-revocable-credentials: true
        revocation-registry-size: 500
        check-non-revoked: true
        use-oob-instead-of-connection: false
    issuer-flow:
        active: false
        use-revocable-credentials: true
        revocation-registry-size: 500
        use-oob-credential-issuance: false
    connection-flow:
        active: false
    credential-issuance-flow:
        active: false
        use-revocable-credentials: true
        revocation-registry-size: 500
        use-oob-credential-issuance: false
    proof-request-flow:
        active: false
        check-non-revoked: true
        revocation-registry-size: 500
        use-oob-proof-requests: false
